---
title: "Homework 4"
author: "Jack Cunningham"
format: pdf
editor: visual
---

# 1.

3.5)

We are tasked with showing that $x_{t} -x_{t-1}=\delta+w_t+y_t-y_{t-1}$ is stationary and $w_t$ and independent of $y_t$.

This is assuming that the model is $x_{t}=\mu_t+y_t$, with $y_t$ a stationary process.

For a time series to be stationary it must have a constant mean that does not depend on $t$ and a covariance function that only depends on lag h.

We first look at the constant mean that does not depend on t:

$$
E[x_t-x_{t-1}]=E[\delta+w_t+y_{t}-y_{t-1}]=\delta+E[y_t]-E[y_{t-1}]
$$

Then, as $y_t,y_{t-1}$ are stationary processes their expected value would be constant and not depend on $t$.

Next we look at the covariance function.

$$
\gamma(0)=Var(x_t-x_{t-1})=Var(\delta+w_t+y_t-y_{t-1})=Var(w_t)+Var(y_t)+Var(y_{t-1})-2Cov(y_t,y_{t-1})
$$

Since $y_t,y_{t-1}$ are stationary processes their covariance depends on lag h. So:

$$
\gamma(0)=\sigma_w^2+2 \gamma_y(0)-2\gamma_y(1)
$$

$$
\gamma(1)=Cov(x_{t}-x_{t-1},x_{t+1}-x_t)=Cov(\delta+w_{t}+y_t-y_{t-1},\delta+w_{t+1}+y_{t+1}-y_{t})
$$

$$
=Cov(y_t,y_{t+1})-Cov(y_t,y_t)-Cov(y_{t-1},y_{t+1})+Cov(y_{t-1},y_t)=\gamma_y(1)-\gamma_y(0)-\gamma_y(2)+\gamma_y(1)=2\gamma_y(1)-\gamma_y(0)-\gamma_y(2)
$$

We can see that $\gamma(1)$ also depends only on lag h.

This pattern continues on, with $\gamma(h)$ depending only on linear combinations of $\gamma_y(h)$ and thus depending only on h.

With this we can say $x_t-x_{t-1}$ is a stationary process.
